export const DEFAULT_CONST = 'auth/DEFAULT_CONST';

export const FETCH_LIST_DATA = 'auth/FETCH_LIST_DATA';
export const FETCH_LIST_DATA_SUCCESS = 'auth/FETCH_LIST_DATA_SUCCESS';
export const FETCH_LIST_DATA_ERROR = 'auth/FETCH_LIST_DATA_ERROR';

export const FETCH_USER_LIST_DATA = 'auth/FETCH_USER_LIST_DATA';
export const FETCH_USER_LIST_DATA_SUCCESS = 'auth/FETCH_USER_LIST_DATA_SUCCESS';
export const FETCH_USER_LIST_DATA_ERROR = 'auth/FETCH_USER_LIST_DATA_ERROR';

export const POST_USER_LIST_DATA = 'auth/POST_USER_LIST_DATA';
export const POST_USER_LIST_DATA_SUCCESS = 'auth/POST_USER_LIST_DATA_SUCCESS';
export const POST_USER_LIST_DATA_ERROR = 'auth/POST_USER_LIST_DATA_ERROR';
